trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@2
  inputs:
    versionSpec: '14.x'
    checkLatest: true

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build the application'

- script: npm test
  displayName: 'Run tests'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'dist'
    artifactName: 'drop'
    publishLocation: 'Container'
